In [14]:
import cx_Oracle

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

oracle_user = "ro_user"
oracle_pass = "ro_user"
oracle_scheme = "aml_evraz"
oracle_host = "192.168.101.13/rnd"
oracle_connection = cx_Oracle.connect(oracle_user, oracle_pass, oracle_host, encoding = "UTF-8", nencoding = "UTF-8")
oracle_cursor = oracle_connection.cursor()

In [20]:
query = """
select P_SUSPIC_KIND, COUNT(*) from {0}.TB_SUSPICIOUSOPERATIONS
GROUP BY P_SUSPIC_KIND
""".format(oracle_scheme)
a = []
for result in oracle_cursor.execute(query):
    print(result)

(1, 221645)
(6, 31452)
(2, 7368)
(4, 81140)
(3, 56193)
(7, 3620)
(0, 139)

In [19]:
a = list(map(lambda x: x[0], a))

In [12]:
list(filter(lambda x: "SUSP" in x, a))

['TB_SUSPICIOUSOPERATIONS',
 'TB_SUSPICIOUSMEMBERS',
 'TB_SUSP_MEMBERS',
 'TB_SUSP_MEMBERS',
 'TB_SUSPICIOUSMEMBERS',
 'TB_SUSPICIOUSOPERATIONS']

In [3]:
%%time
query = """
select COLUMN_NAME from ALL_TAB_COLUMNS where TABLE_NAME='TB_OFFLINEOPERATIONS'
"""
print("\n".join(map(str, oracle_cursor.execute(query))))

('P_CURRENCYAMOUNT',)
('P_BASEAMOUNT',)
('P_OPERATIONDATETIME',)
('P_CURRENCYCODE',)
('P_BRANCH',)
('P_ORDERNUMBER',)
('P_BANKOPERATIONID',)
('P_ISSUEDBID',)
('ID',)
('P_USERNAME',)
('RISK_REMARK',)
('IS_CALCED',)
('RISK_CHANGE_DATE',)
('RISK_LEVEL',)
('MEMBERS_RISK',)
('PRODUCT_RISK',)
('PRODUCT_ID',)
('ABIS_PRODUCT',)
('P_BASEAMOUNT_ALL',)
('IS_BANK',)
('IN_P_ONLINE_STATUS',)
('P_CRITERIADIFFICULTIES',)
('P_REASONCODE',)
('P_IS_ONLINE',)
('P_SDP',)
('P_PROPERTYNUMBER',)
('P_PROPERTY',)
('P_DOCSUSPIC',)
('P_DOCTYPE',)
('P_HISTORY',)
('CHANGEDATE',)
('P_DATE_UPDATE',)
('P_DATE_INSERT',)
('P_TOEXTRACTBOOL',)
('P_CHECKED',)
('P_OPERATIONREASON',)
('P_OPERATIONSTATUS',)
('P_DOCCATEGORY',)
('P_DOCDATE',)
('P_DOCNUMBER',)
('P_EKNPCODE',)
('P_OPERATIONDATE',)
('P_INNER_SUSP_CHECK',)
('RISK_CHECKED',)
('P_SDP',)
('P_WAS_SEND',)
('P_HISTORY',)
('P_ORIG_OPER_NUMBER',)
('P_BS_OPER_TYPE',)
('P_KFM_OPER_REASON',)
('P_PROPERTYNUMBER',)
('P_PROPERTY',)
('P_DOCSUSPIC',)
('P_DOCTYPE',)
('CHANGEDATE',)
('P_DATE_UPDATE',)
('P_DATE_INSERT',)
('P_TOEXTRACTBOOL',)
('P_CHECKED',)
('P_OPERATIONREASON',)
('P_OPERATIONSTATUS',)
('P_DOCCATEGORY',)
('P_DOCDATE',)
('P_DOCNUMBER',)
('P_EKNPCODE',)
('P_CURRENCYAMOUNT',)
('P_BASEAMOUNT',)
('P_OPERATIONDATETIME',)
('P_CURRENCYCODE',)
('P_BRANCH',)
('P_ORDERNUMBER',)
('P_BANKOPERATIONID',)
('P_ISSUEDBID',)
('ID',)
CPU times: user 636 Âµs, sys: 2.58 ms, total: 3.22 ms
Wall time: 5.91 ms

In [15]:
%%time

query = """
SELECT * 
FROM {0}.TB_SUSPICIOUSOPERATIONS
WHERE ROWNUM < 10
""".format(oracle_scheme)

df = pd.read_sql(query, oracle_connection)

CPU times: user 9.29 ms, sys: 6.01 ms, total: 15.3 ms
Wall time: 127 ms

In [17]:
df.columns

Index(['ID', 'P_ISSUEDBID', 'P_BANKOPERATIONID', 'P_ORDERNUMBER', 'P_BRANCH',
       'P_CURRENCYCODE', 'P_OPERATIONDATETIME', 'P_BASEAMOUNT',
       'P_CURRENCYAMOUNT', 'P_EKNPCODE', 'P_DOCNUMBER', 'P_DOCDATE',
       'P_DOCCATEGORY', 'P_OPERATIONSTATUS', 'P_OPERATIONREASON',
       'P_MESS_NUMBER', 'P_MESS_DATE', 'P_MESS_KIND', 'P_MESS_STATUS',
       'P_SUSPIC_KIND', 'P_SUSPICIOUSTYPECODE', 'P_CRITERIAFIRST',
       'P_CRITERIASECOND', 'P_CRITERIATHIRD', 'P_CRITERIADIFFICULTIES',
       'P_OPERATIONEXTRAINFO', 'P_OFFLINEOPERATIONID', 'P_SENDTOKFMBOOL',
       'P_DATE_INSERT', 'P_DATE_UPDATE', 'P_USERNAME', 'P_OPERATION_LIST',
       'P_COMMENT', 'P_APPROVE', 'P_ATTACHMENT_COMMENT', 'P_HISTORY',
       'CHANGEDATE', 'P_DOCTYPE', 'P_DOCSUSPIC', 'P_PROPERTY',
       'P_PROPERTYNUMBER', 'P_ORIG_OPER_REASON', 'P_DETECTED_BY_FILIAL',
       'P_USER_DETECTED', 'P_COUNTER_MEASURE', 'P_OPERATION_CNT',
       'P_OPERATION_CNT_M'],
      dtype='object')

In [9]:
%%time
df.to_csv("../data/off_ops.csv", index=False)

CPU times: user 2min 54s, sys: 5.16 s, total: 3min
Wall time: 3min

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8222263 entries, 0 to 8222262
Data columns (total 21 columns):
ID                     int64
P_ISSUEDBID            int64
P_BANKOPERATIONID      object
P_BRANCH               object
P_CURRENCYCODE         object
P_OPERATIONDATETIME    datetime64[ns]
P_BASEAMOUNT           float64
P_CURRENCYAMOUNT       float64
P_EKNPCODE             object
P_DOCNUMBER            object
P_DOCDATE              object
P_DOCCATEGORY          int64
P_OPERATIONREASON      object
P_TOEXTRACTBOOL        int64
P_DATE_INSERT          datetime64[ns]
CHANGEDATE             datetime64[ns]
P_KFM_OPER_REASON      float64
P_BS_OPER_TYPE         object
P_ORIG_OPER_NUMBER     object
P_WAS_SEND             int64
P_OPERATIONDATE        datetime64[ns]
dtypes: datetime64[ns](4), float64(3), int64(5), object(9)
memory usage: 1.3+ GB

In [6]:
of = pd.read_csv("../data/off_ops.csv")

/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (2,4,10,18,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [8]:
col = "P_DATE_UPDATE"

to_drop = ["P_DATE_UPDATE", "P_HISTORY", "P_ORDERNUMBER", "P_OPERATIONSTATUS", "P_CHECKED", "P_DATE_UPDATE", 
           "P_DOCTYPE", "P_DOCSUSPIC", "P_PROPERTY", "P_PROPERTYNUMBER", "RISK_CHECKED", "P_SDP", "RISK_CHECKED",
           "P_INNER_SUSP_CHECK"]

", ".join(filter(lambda x: x not in to_drop, of.columns))

'ID, P_ISSUEDBID, P_BANKOPERATIONID, P_BRANCH, P_CURRENCYCODE, P_OPERATIONDATETIME, P_BASEAMOUNT, P_CURRENCYAMOUNT, P_EKNPCODE, P_DOCNUMBER, P_DOCDATE, P_DOCCATEGORY, P_OPERATIONREASON, P_TOEXTRACTBOOL, P_DATE_INSERT, CHANGEDATE, P_KFM_OPER_REASON, P_BS_OPER_TYPE, P_ORIG_OPER_NUMBER, P_WAS_SEND, P_OPERATIONDATE'

In [23]:
def df_categorical_variables_stat(df, max_cardinality=200):
    for colname in df.columns:
        print('next_column: {}'.format(colname))
        uniq_vals = df[colname].unique()
        nunique = len(uniq_vals)
        print("# of uniqs: {}".format(nunique))
        if nunique < max_cardinality:
            print('Viable Categorical. Value counts:')
            print(df[colname].value_counts(dropna=False))
        else:
            print('High cardinality/Non categorical')
        print((('-' * 80) + '\n')*3)
df_categorical_variables_stat(of)

next_column: ID
# of uniqs: 300000
High cardinality/Non categorical
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_ISSUEDBID
# of uniqs: 5
Viable Categorical. Value counts:
5    217691
3     57810
1     22234
4      1760
2       505
Name: P_ISSUEDBID, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_BANKOPERATIONID
# of uniqs: 300000
High cardinality/Non categorical
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_ORDERNUMBER
# of uniqs: 1
Viable Categorical. Value counts:
NaN    300000
Name: P_ORDERNUMBER, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_BRANCH
# of uniqs: 36
Viable Categorical. Value counts:
0        81210
0        63187
7        48430
12       11382
5         9113
3         8769
9         7830
7         6276
6         5651
4         5301
12        4457
5         4176
9         3932
6         3663
19        3138
4         2838
15        2729
3         2529
8         2496
14        2443
10        2335
15        2317
19        2092
13        2035
11        2033
8         1930
13        1447
14        1283
10        1199
11        1166
17         979
17         583
20         579
20         317
WAY 4      154
-1           1
Name: P_BRANCH, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_CURRENCYCODE
# of uniqs: 43
Viable Categorical. Value counts:
398    282499
840     10130
643      3460
978      2130
980       291
784       210
826       168
949       159
124       129
764       127
203       115
417        69
156        68
702        43
348        36
360        36
933        33
356        33
985        30
36         24
818        22
458        21
704        20
410        20
376        19
981        16
554        14
144        14
710         9
392         7
484         7
344         6
944         5
608         5
752         5
975         4
756         4
986         3
462         3
214         3
480         1
952         1
32          1
Name: P_CURRENCYCODE, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_OPERATIONDATETIME
# of uniqs: 28697
High cardinality/Non categorical
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_BASEAMOUNT
# of uniqs: 49156
High cardinality/Non categorical
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_CURRENCYAMOUNT
# of uniqs: 44723
High cardinality/Non categorical
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_EKNPCODE
# of uniqs: 136
Viable Categorical. Value counts:
NaN       147165
 321.0     58081
 119.0     29496
 324.0     11252
 311.0      9512
 852.0      5845
 869.0      5066
 314.0      4819
 421.0      3363
 423.0      3300
 322.0      2103
 710.0      1799
 429.0      1793
 419.0      1684
 312.0      1432
 411.0      1160
 890.0      1045
 490.0       994
 856.0       813
 911.0       695
 0.0         658
 912.0       652
 223.0       587
 33.0        540
 841.0       533
 342.0       449
 859.0       403
 331.0       342
 213.0       331
 341.0       305
           ...
 19.0          5
 56.0          5
 230.0         5
 835.0         4
 993.0         4
 329.0         4
 663.0         4
 991.0         4
 221.0         3
 42.0          3
 57.0          3
 837.0         2
 15.0          2
 132.0         2
 318.0         2
 815.0         2
 690.0         2
 610.0         2
 319.0         1
 831.0         1
 812.0         1
 840.0         1
 333.0         1
 21.0          1
 979.0         1
 51.0          1
 730.0         1
 31.0          1
 131.0         1
 917.0         1
Name: P_EKNPCODE, Length: 136, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_DOCNUMBER
# of uniqs: 253550
High cardinality/Non categorical
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_DOCDATE
# of uniqs: 101851
High cardinality/Non categorical
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_DOCCATEGORY
# of uniqs: 13
Viable Categorical. Value counts:
 10    112257
 2      79273
 4      61942
 1      17811
 3      17355
 11      5514
-1       2997
 25      2256
 24       217
 7        207
 8        145
 16        19
 9          7
Name: P_DOCCATEGORY, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_OPERATIONSTATUS
# of uniqs: 1
Viable Categorical. Value counts:
1    300000
Name: P_OPERATIONSTATUS, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_OPERATIONREASON
# of uniqs: 74280
High cardinality/Non categorical
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_CHECKED
# of uniqs: 1
Viable Categorical. Value counts:
2    300000
Name: P_CHECKED, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_TOEXTRACTBOOL
# of uniqs: 2
Viable Categorical. Value counts:
-1    150563
 1    149437
Name: P_TOEXTRACTBOOL, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_DATE_INSERT

# of uniqs: 8309
High cardinality/Non categorical
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_DATE_UPDATE
# of uniqs: 7
Viable Categorical. Value counts:
NaN                    299994
2017-01-05 12:42:47         1
2017-03-14 16:37:12         1
2017-01-05 14:33:19         1
2017-01-05 14:35:27         1
2017-03-14 16:34:36         1
2017-01-05 14:30:24         1
Name: P_DATE_UPDATE, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: CHANGEDATE
# of uniqs: 8309
High cardinality/Non categorical
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_DOCTYPE
# of uniqs: 1
Viable Categorical. Value counts:
NaN    300000
Name: P_DOCTYPE, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_DOCSUSPIC
# of uniqs: 1
Viable Categorical. Value counts:
NaN    300000
Name: P_DOCSUSPIC, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_PROPERTY
# of uniqs: 3
Viable Categorical. Value counts:
NaN     299993
 4.0         4
 2.0         3
Name: P_PROPERTY, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_PROPERTYNUMBER
# of uniqs: 1
Viable Categorical. Value counts:
NaN    300000
Name: P_PROPERTYNUMBER, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_KFM_OPER_REASON
# of uniqs: 12
Viable Categorical. Value counts:
 13.0    217062
NaN       71423
 10.0      6792
 15.0      1869
 2.0       1794
 11.0       496
 5.0        255
 29.0       145
 9.0        113
 6.0         38
 17.0         7
 1.0          6
Name: P_KFM_OPER_REASON, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_BS_OPER_TYPE
# of uniqs: 190
Viable Categorical. Value counts:
5               61105
13              49571
10307           21819
35338           20045
5               12910
35459           12156
35458           12118
10306           11039
14300            9856
0-1-62-113       8006
13               7576
33965            6913
33965            5994
34145            5046
13200            4828
0-1-62-615       4698
34145            4258
33725            2733
14400            2501
33725            2432
35338            2263
10201            2084
0-1-71-616       1734
60               1634
2                1464
35458            1296
10306            1296
13001            1264
36924            1264
35459            1257
                ...
1-1-1-107           3
1021                3
1-1-63-120          3
1049                3
1-200-21-141        3
0-1-63-100          2
0-1-71-0            2
0-1-62-613          2
9                   2
182                 2
1-1-63-122          2
0-1-71-614          2
0-200-11-147        2
0-200-11-307        2
0-200-11-308        1
444                 1
0-1-73-4            1
0-200-41-8          1
0-200-11-331        1
1-1-71-25           1
0-1-63-315          1
1-1-71-614          1
0-1-80-601          1
0-200-11-321        1
1-1-62-52           1
1045                1
0-200-11-58         1
22120               1
1025                1
1-1-62-613          1
Name: P_BS_OPER_TYPE, Length: 190, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_ORIG_OPER_NUMBER
# of uniqs: 300000
High cardinality/Non categorical
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_HISTORY
# of uniqs: 46952
High cardinality/Non categorical
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_WAS_SEND
# of uniqs: 3
Viable Categorical. Value counts:
0    299887
1        90
2        23
Name: P_WAS_SEND, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_SDP
# of uniqs: 1
Viable Categorical. Value counts:
NaN    300000
Name: P_SDP, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: RISK_CHECKED
# of uniqs: 1
Viable Categorical. Value counts:
NaN    300000
Name: RISK_CHECKED, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_INNER_SUSP_CHECK
# of uniqs: 1
Viable Categorical. Value counts:
NaN    300000
Name: P_INNER_SUSP_CHECK, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

next_column: P_OPERATIONDATE
# of uniqs: 5
Viable Categorical. Value counts:
2017-01-04 00:00:00    223666
2017-01-05 00:00:00     71693
2017-01-03 00:00:00      1917
2017-01-02 00:00:00      1469
2017-01-01 00:00:00      1255
Name: P_OPERATIONDATE, dtype: int64
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

In [13]:
of.memory_usage(deep=True)

Index                         80
ID                       2400000
P_ISSUEDBID              2400000
P_BANKOPERATIONID       15818368
P_ORDERNUMBER            2400000
P_BRANCH                16251298
P_CURRENCYCODE           2400000
P_OPERATIONDATETIME     22800000
P_BASEAMOUNT             2400000
P_CURRENCYAMOUNT         2400000
P_EKNPCODE               2400000
P_DOCNUMBER             14586593
P_DOCDATE               22800000
P_DOCCATEGORY            2400000
P_OPERATIONSTATUS        2400000
P_OPERATIONREASON       84752599
P_CHECKED                2400000
P_TOEXTRACTBOOL          2400000
P_DATE_INSERT           22800000
P_DATE_UPDATE            9600264
CHANGEDATE              22800000
P_DOCTYPE                2400000
P_DOCSUSPIC              2400000
P_PROPERTY               2400000
P_PROPERTYNUMBER         2400000
P_KFM_OPER_REASON        2400000
P_BS_OPER_TYPE          14047225
P_ORIG_OPER_NUMBER      15677918
P_HISTORY              598458402
P_WAS_SEND               2400000
P_SDP                    2400000
RISK_CHECKED             2400000
P_INNER_SUSP_CHECK       2400000
P_OPERATIONDATE         22800000
dtype: int64